console.log("---------𝙈𝘼𝙎𝘼𝙄 𝙎𝘾𝙃𝙊𝙊𝙇 𝙍𝙀𝙋𝙊𝙍𝙏 𝘾𝘼𝙍𝘿---------")
let stu1 = ("name = BHANU PRATAP          class = 6 " )
let stu2 = ("batch = 006                 ROLL NO = 69 " )  
let stu3 = ("school = DPS                SACTION = B2 ")

console.log (stu1)
console.log (stu2)
console.log (stu3)
console.log("----Subject-----------------Marks-----------")
let h1 = (" Hindi                         46 " )
let  e1= (" English                       95 " )  
let a1 = (" Accounts                      99 ")
console.log (h1)
console.log (e1)
console.log (a1)
console.log("--------------------------------------------")
